Switch bash codingstyle from tab to spaces
Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>

diff --git a/image-density-fixer b/image-density-fixer
--- a/image-density-fixer
+++ b/image-density-fixer
@@ -5,29 +5,29 @@
 ## Makes debuggers' life easier - Unofficial Bash Strict Mode
 ## BASHDOC: Shell Builtin Commands - Modifying Shell Behavior - The Set Builtin
 set \
-	-o errexit \
-	-o errtrace \
-	-o nounset \
-	-o pipefail
+    -o errexit \
+    -o errtrace \
+    -o nounset \
+    -o pipefail
 
 ## Runtime Dependencies Checking
 declare\
-	runtime_dependency_checking_result=still-pass\
-	required_software
+    runtime_dependency_checking_result=still-pass\
+    required_software
 
 for required_command in \
-	basename \
-	dirname \
-	realpath; do
-	if ! command -v "${required_command}" &>/dev/null; then
-		runtime_dependency_checking_result=fail
+    basename \
+    dirname \
+    realpath; do
+    if ! command -v "${required_command}" &>/dev/null; then
+        runtime_dependency_checking_result=fail
 
-		case "${required_command}" in
-			basename \
-			|dirname \
-			|realpath)
-				required_software='GNU Coreutils'
-				;;
+        case "${required_command}" in
+            basename \
+            |dirname \
+            |realpath)
+                required_software='GNU Coreutils'
+                ;;
             bc)
                 required_software='GNU bc'
                 ;;
@@ -42,38 +42,38 @@ for required_command in \
                 ;;
         esac
 
-		printf -- \
-			'Error: This program requires "%s" to be installed and its executables in the executable searching paths.\n' \
-			"${required_software}" \
-			1>&2
-		unset required_software
-	fi
+        printf -- \
+            'Error: This program requires "%s" to be installed and its executables in the executable searching paths.\n' \
+            "${required_software}" \
+            1>&2
+        unset required_software
+    fi
 done; unset required_command required_software
 
 if [ "${runtime_dependency_checking_result}" = fail ]; then
-	printf -- \
-		'Error: Runtime dependency checking fail, the progrom cannot continue.\n' \
-		1>&2
-	exit 1
+    printf -- \
+        'Error: Runtime dependency checking fail, the progrom cannot continue.\n' \
+        1>&2
+    exit 1
 fi; unset runtime_dependency_checking_result
 
 ## Non-overridable Primitive Variables
 ## BASHDOC: Shell Variables » Bash Variables
 ## BASHDOC: Basic Shell Features » Shell Parameters » Special Parameters
 if [ -v 'BASH_SOURCE[0]' ]; then
-	RUNTIME_EXECUTABLE_PATH="$(realpath --strip "${BASH_SOURCE[0]}")"
-	RUNTIME_EXECUTABLE_FILENAME="$(basename "${RUNTIME_EXECUTABLE_PATH}")"
-	RUNTIME_EXECUTABLE_NAME="${RUNTIME_EXECUTABLE_FILENAME%.*}"
-	RUNTIME_EXECUTABLE_DIRECTORY="$(dirname "${RUNTIME_EXECUTABLE_PATH}")"
-	RUNTIME_COMMANDLINE_BASECOMMAND="${0}"
-	# We intentionally leaves these variables for script developers
-	# shellcheck disable=SC2034
-	declare -r \
-		RUNTIME_EXECUTABLE_PATH \
-		RUNTIME_EXECUTABLE_FILENAME \
-		RUNTIME_EXECUTABLE_NAME \
-		RUNTIME_EXECUTABLE_DIRECTORY \
-		RUNTIME_COMMANDLINE_BASECOMMAND
+    RUNTIME_EXECUTABLE_PATH="$(realpath --strip "${BASH_SOURCE[0]}")"
+    RUNTIME_EXECUTABLE_FILENAME="$(basename "${RUNTIME_EXECUTABLE_PATH}")"
+    RUNTIME_EXECUTABLE_NAME="${RUNTIME_EXECUTABLE_FILENAME%.*}"
+    RUNTIME_EXECUTABLE_DIRECTORY="$(dirname "${RUNTIME_EXECUTABLE_PATH}")"
+    RUNTIME_COMMANDLINE_BASECOMMAND="${0}"
+    # We intentionally leaves these variables for script developers
+    # shellcheck disable=SC2034
+    declare -r \
+        RUNTIME_EXECUTABLE_PATH \
+        RUNTIME_EXECUTABLE_FILENAME \
+        RUNTIME_EXECUTABLE_NAME \
+        RUNTIME_EXECUTABLE_DIRECTORY \
+        RUNTIME_COMMANDLINE_BASECOMMAND
 fi
 declare -ar RUNTIME_COMMANDLINE_ARGUMENTS=("${@}")
 
@@ -97,46 +97,46 @@ init(){
     local \
         image_file
 
-	if ! \
+    if ! \
         process_commandline_arguments \
             width_in_cm \
             height_in_cm \
             image_file \
             is_dry_run; then
-		printf -- \
-			'Error: Invalid command-line parameters.\n' \
-			1>&2
+        printf -- \
+            'Error: Invalid command-line parameters.\n' \
+            1>&2
 
-		printf '\n' # separate error message and help message
-		print_help
-		exit 1
-	fi
+        printf '\n' # separate error message and help message
+        print_help
+        exit 1
+    fi
 
-	width_in_px="$(
+    width_in_px="$(
         identify \
             -format %w \
             "${image_file}"
-	)"
-	height_in_px="$(
+    )"
+    height_in_px="$(
         identify \
             -format %h \
             "${image_file}"
-	)"
+    )"
 
-	# 1 inch = 2.54 centimeters
-	# https://en.wikipedia.org/wiki/Inch
-	width_in_inch="$(
+    # 1 inch = 2.54 centimeters
+    # https://en.wikipedia.org/wiki/Inch
+    width_in_inch="$(
         printf --\
             "%s / 2.54\\n" \
             "${width_in_cm}" \
             | bc --mathlib
-	)"
-	height_in_inch="$(
+    )"
+    height_in_inch="$(
         printf --\
             "%s / 2.54\\n" \
             "${height_in_cm}" \
             | bc --mathlib
-	)"
+    )"
 
     horizontal_dpi="$(
         printf --\
@@ -155,48 +155,48 @@ init(){
             | sed 's/\..*$//' # Remove fraction part of decimal
     )"
 
-	if test "${is_dry_run}" != false; then
-		printf -- \
-			'The resulting horizontal dpi: %s\n' \
-			"${horizontal_dpi}"
-		printf -- \
-			'The resulting vertical_dpi dpi: %s\n' \
-			"${vertical_dpi}"
-		printf -- \
-			'The resulting mogrify command:\n    '
+    if test "${is_dry_run}" != false; then
+        printf -- \
+            'The resulting horizontal dpi: %s\n' \
+            "${horizontal_dpi}"
+        printf -- \
+            'The resulting vertical dpi: %s\n' \
+            "${vertical_dpi}"
+        printf -- \
+            'The resulting mogrify command:\n    '
         echo mogrify \
             -density "${horizontal_dpi}"x"${vertical_dpi}" \
             "${image_file}"
-	else
+    else
         mogrify \
             -density "${horizontal_dpi}"x"${vertical_dpi}" \
             "${image_file}"
     fi
 
-	exit 0
+    exit 0
 }; declare -fr init
 
 print_help(){
-	# Backticks in help message is Markdown's <code> markup
-	# shellcheck disable=SC2016
-	{
-		printf '# Help Information for %s #\n' \
-			"${RUNTIME_COMMANDLINE_BASECOMMAND}"
-		printf '## SYNOPSIS ##\n'
-		printf '* `"%s" _command-line_options_ _real_width_in_centimeters_ _real_height_in_centimeters_ _image_file_`\n\n' \
-			"${RUNTIME_COMMANDLINE_BASECOMMAND}"
+    # Backticks in help message is Markdown's <code> markup
+    # shellcheck disable=SC2016
+    {
+        printf '# Help Information for %s #\n' \
+            "${RUNTIME_COMMANDLINE_BASECOMMAND}"
+        printf '## SYNOPSIS ##\n'
+        printf '* `"%s" _command-line_options_ _real_width_in_centimeters_ _real_height_in_centimeters_ _image_file_`\n\n' \
+            "${RUNTIME_COMMANDLINE_BASECOMMAND}"
 
-		printf '## COMMAND-LINE OPTIONS ##\n'
-		printf '### `-d` / `--debug` ###\n'
-		printf 'Enable script debugging\n\n'
+        printf '## COMMAND-LINE OPTIONS ##\n'
+        printf '### `-d` / `--debug` ###\n'
+        printf 'Enable script debugging\n\n'
 
-		printf '### `--dry-run` ###\n'
-		printf "Don't actually apply modification to the image, just print what we gonna do.\\n\\n"
+        printf '### `--dry-run` ###\n'
+        printf "Don't actually apply modification to the image, just print what we gonna do.\\n\\n"
 
-		printf '### `-h` / `--help` ###\n'
-		printf 'Print this message\n\n'
-	}
-	return 0
+        printf '### `-h` / `--help` ###\n'
+        printf 'Print this message\n\n'
+    }
+    return 0
 }; declare -fr print_help;
 
 process_commandline_arguments() {
@@ -211,35 +211,35 @@ process_commandline_arguments() {
     image_file_ref="${1}"; shift 1
     is_dry_run_ref="${1}"; shift 1
 
-	if [ "${#RUNTIME_COMMANDLINE_ARGUMENTS[@]}" -eq 0 ]; then
+    if [ "${#RUNTIME_COMMANDLINE_ARGUMENTS[@]}" -eq 0 ]; then
         print_help
         exit 0
-	fi
+    fi
 
-	# Modifyable parameters for parsing by consuming
-	local -a parameters=("${RUNTIME_COMMANDLINE_ARGUMENTS[@]}")
+    # Modifyable parameters for parsing by consuming
+    local -a parameters=("${RUNTIME_COMMANDLINE_ARGUMENTS[@]}")
 
-	# Normally we won't want debug traces to appear during parameter parsing, so we add this flag and defer its activation till returning
-	local enable_debug=false
+    # Normally we won't want debug traces to appear during parameter parsing, so we add this flag and defer its activation till returning
+    local enable_debug=false
 
-	while true; do
-		if [ "${#parameters[@]}" -eq 0 ]; then
-			break
-		else
-			case "${parameters[0]}" in
-				--debug \
-				|-d)
-					enable_debug=true
-					;;
+    while true; do
+        if [ "${#parameters[@]}" -eq 0 ]; then
+            break
+        else
+            case "${parameters[0]}" in
+                --debug \
+                |-d)
+                    enable_debug=true
+                    ;;
                 --dry-run)
                     is_dry_run_ref=true
                     ;;
-				--help \
-				|-h)
-					print_help
-					exit 0
-					;;
-				*)
+                --help \
+                |-h)
+                    print_help
+                    exit 0
+                    ;;
+                *)
                     if [ "${#parameters[@]}" -ne 3 ]; then
                         printf -- \
                             '%s: Error: Invalid command-line argument count!\n' \
@@ -258,59 +258,59 @@ process_commandline_arguments() {
                             parameters=("${parameters[@]}")
                         fi
                     fi
-					;;
-			esac
-			# shift array by 1 = unset 1st then repack
-			unset 'parameters[0]'
-			if [ "${#parameters[@]}" -ne 0 ]; then
-				parameters=("${parameters[@]}")
-			fi
-		fi
-	done
+                    ;;
+            esac
+            # shift array by 1 = unset 1st then repack
+            unset 'parameters[0]'
+            if [ "${#parameters[@]}" -ne 0 ]; then
+                parameters=("${parameters[@]}")
+            fi
+        fi
+    done
 
-	if ! test -v width_in_cm_ref \
+    if ! test -v width_in_cm_ref \
         || ! test -v height_in_cm_ref \
         || ! test -v image_file_ref; then
         print_help
         exit 0
     fi
 
-	if [ "${enable_debug}" = true ]; then
-		trap 'trap_return "${FUNCNAME[0]}"' RETURN
-		set -o xtrace
-	fi
-	return 0
+    if [ "${enable_debug}" = true ]; then
+        trap 'trap_return "${FUNCNAME[0]}"' RETURN
+        set -o xtrace
+    fi
+    return 0
 }; declare -fr process_commandline_arguments
 
 ## Traps: Functions that are triggered when certain condition occurred
 ## Shell Builtin Commands » Bourne Shell Builtins » trap
 trap_errexit(){
-	printf \
-		'An error occurred and the script is prematurely aborted\n' \
-		1>&2
-	return 0
+    printf \
+        'An error occurred and the script is prematurely aborted\n' \
+        1>&2
+    return 0
 }; declare -fr trap_errexit; trap trap_errexit ERR
 
 trap_exit(){
-	return 0
+    return 0
 }; declare -fr trap_exit; trap trap_exit EXIT
 
 trap_return(){
-	local returning_function="${1}"
+    local returning_function="${1}"
 
-	printf \
-		'DEBUG: %s: returning from %s\n' \
-		"${FUNCNAME[0]}" \
-		"${returning_function}" \
-		1>&2
+    printf \
+        'DEBUG: %s: returning from %s\n' \
+        "${FUNCNAME[0]}" \
+        "${returning_function}" \
+        1>&2
 }; declare -fr trap_return
 
 trap_interrupt(){
-	printf '\n' # Separate previous output
-	printf \
-		'Recieved SIGINT, script is interrupted.' \
-		1>&2
-	return 1
+    printf '\n' # Separate previous output
+    printf \
+        'Recieved SIGINT, script is interrupted.' \
+        1>&2
+    return 1
 }; declare -fr trap_interrupt; trap trap_interrupt INT
 
 init "${@}"
